import { WebsiteSettings, WebsiteSection } from '@/types/database';

export const INITIAL_BUSINESS_SETTINGS: WebsiteSettings = {
  id: 'current',
  brand_name: 'Desi Fusion Bites',
  tagline: 'Purana Swad Naya Tadka',
  logo_url: null,
  favicon_url: null,
  proprietor: 'Aruna Harlalka',
  contact_person: 'Priya Harlalka',
  phone: '9051941774',
  whatsapp: '9051941774',
  email: 'desifusionbites@gmail.com',
  address_line1: '275 Dwarika Jungle Road',
  address_line2: 'P.O. Bhadrakali, P.S. Uttarpara',
  district: 'Hooghly District',
  state: 'West Bengal',
  pincode: '712232',
  country: 'India',
  fssai_license: '12826999000591',
  opening_hours: '8:00 AM to 8:00 PM',
  instagram_handle: '@desifusionbite',
  instagram_url: 'https://instagram.com/desifusionbite',
  youtube_handle: '@desifusionbite',
  youtube_url: 'https://youtube.com/@desifusionbite',
  google_business_url: 'https://maps.google.com',
  maps_embed_url: null,
  hero_badge: 'Packaged Foods & Indian Snacks',
  hero_title: 'Purana Swad, Naya Tadka',
  hero_subtitle: 'Indian packaged foods and snacks by Desi Fusion Bites, located in Hooghly District, West Bengal.',
  hero_cta_text: 'Explore Products',
  hero_cta_url: '/products',
  hero_image_url: null,
  story_title: 'About Desi Fusion Bites',
  story_paragraphs: [
    'Desi Fusion Bites is an Indian packaged food brand managed by proprietor Aruna Harlalka and contact lead Priya Harlalka.',
    'Operating under FSSAI License No. 12826999000591, located at 275 Dwarika Jungle Road, P.O. Bhadrakali, P.S. Uttarpara, Hooghly District, West Bengal - 712232.'
  ],
  about_image_url: null,
  footer_text: 'Packaged food products by Desi Fusion Bites.',
  delivery_fee: 60,
  free_delivery_enabled: false,
  free_delivery_min_amount: null,
};

export const INITIAL_SECTIONS: WebsiteSection[] = [
  { id: 'hero', name: 'Hero Banner', display_order: 1, is_enabled: true, title: 'Purana Swad, Naya Tadka', subtitle: 'Desi Fusion Bites' },
  { id: 'categories', name: 'Product Categories', display_order: 2, is_enabled: true, title: 'Product Categories', subtitle: 'Browse available packaged food categories' },
  { id: 'featured_products', name: 'Featured Products', display_order: 3, is_enabled: true, title: 'Featured Products', subtitle: 'Featured packaged food selections' },
  { id: 'story_preview', name: 'Brand Story Preview', display_order: 4, is_enabled: true, title: 'About Desi Fusion Bites', subtitle: 'Business background and details' },
  { id: 'wholesale_cta', name: 'Wholesale & Distributor Banner', display_order: 5, is_enabled: true, title: 'Wholesale & Distributor Inquiries', subtitle: 'Commercial supply for distributors, retailers, and resellers' },
  { id: 'testimonials', name: 'Customer Testimonials', display_order: 6, is_enabled: true, title: 'Customer Feedback', subtitle: 'Feedback from verified customers' },
  { id: 'contact_preview', name: 'Visit & Contact Us', display_order: 7, is_enabled: true, title: 'Contact Us', subtitle: 'Located in Hooghly District, West Bengal.' },
];
